name: Release and Publish to PyPI

on:
  push:
    branches:
      - prod
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version

      - name: Auto-bump version
        run: |
          bump2version patch --allow-dirty
        env:
          BUMPVERSION_CURRENT_VERSION: $(python setup.py --version)

      - name: Commit bumped version
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add setup.py
            git commit -m "Bump version [skip ci]"
            git push

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Build Package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
